#!/bin/sh -x 
rm -rf htdocs
cvs -d zamboni@cvs.sourceforge.net:/cvsroot/grabcartoons export -Dtoday -d htdocs grabcartoons-webpage
chmod -R go=u,go-w htdocs
cd htdocs
ln -s grabcartoons.html index.html
